import { createServer } from 'node:http';
import { readFile, mkdir, writeFile } from 'node:fs/promises';
import { fileURLToPath, pathToFileURL } from 'node:url';
import path from 'node:path';
import assert from 'node:assert/strict';
const root = fileURLToPath(new URL('../', import.meta.url));
const tools = process.env.DSH_TEST_MODULES;
const { build } = await import(tools ? pathToFileURL(path.join(tools, 'esbuild/lib/main.js')).href : 'esbuild');
const { chromium } = await import(tools ? pathToFileURL(path.join(tools, 'playwright-core/index.mjs')).href : 'playwright-core');
const out = path.resolve(process.env.DSH_TEST_OUTPUT || path.join(root, '../../work/browser-test'));
await mkdir(out, { recursive: true });
const fixture = await build({ absWorkingDir: root, entryPoints: ['test/fixture.jsx'], bundle: true, write: false,
  format: 'iife', platform: 'browser', nodePaths: tools ? [tools] : [] });
const html = `<!doctype html><meta charset="utf-8"><style>
*{box-sizing:border-box}body{margin:0;background:#f8fafb;color:#344454;font:15px system-ui;--dsw-alias-label-primary:#344454;--dsw-alias-bg-base:#f8fafb}#app{display:flex;height:100vh}aside{width:235px;background:#edf1f4;padding:30px 18px}aside small{display:block;margin:8px 0 30px;color:#84919d}aside [role=treeitem]{padding:12px 6px;display:flex;gap:10px}aside [role=treeitem]>span:last-child{margin-left:auto;font-size:10px}main{flex:1;min-width:0}header{height:76px;border-bottom:1px solid #879eaa22;display:flex;align-items:center;justify-content:space-between;padding:0 28px}[data-conversation-content]{height:calc(100vh - 76px);padding:40px 8%;display:flex;flex-direction:column}#messages{flex:1;overflow:auto}[data-chat-flow-kind]{padding:14px 0;line-height:1.8}[data-chat-flow-kind=user]{margin-left:auto;background:#e8eef2;border-radius:16px;padding:12px 18px;width:max-content;max-width:85%}[data-composer-seat]{border:1px solid #879eaa44;border-radius:20px;padding:22px;background:#fff}[data-composer-input]{outline:none;min-height:28px}pre{background:#edf1f4;border-radius:10px;padding:16px}header span{font-weight:500}@media(max-width:600px){aside{display:none}header{padding:0 15px}}
</style><div id="app"></div><script src="/fixture.js"></script><script src="/client.js"></script>`;
const server = createServer(async (req, res) => {
  res.setHeader('Content-Type', req.url.endsWith('.js') ? 'text/javascript' : 'text/html');
  res.end(req.url === '/fixture.js' ? fixture.outputFiles[0].contents : req.url === '/client.js' ? await readFile(path.join(root, 'lib/client.js')) : html);
});
await new Promise(resolve => server.listen(0, '127.0.0.1', resolve));
const browser = await chromium.launch({ executablePath: process.env.DSH_BROWSER || 'C:/Program Files (x86)/Microsoft/Edge/Application/msedge.exe', headless: true });
const context = await browser.newContext({ viewport: { width: 1200, height: 800 } });
const page = await context.newPage(), errors = [], checks = [];
page.on('pageerror', error => errors.push(error.message));
const check = (name, condition) => { assert.ok(condition, name); checks.push(name); console.log(`PASS ${name}`); };
try {
  await page.goto(`http://127.0.0.1:${server.address().port}`);
  await page.waitForSelector('.ld-surface');
  check('history mount has no entrance animations', await page.locator('#messages').evaluate(el => el.getAnimations({ subtree: true }).length === 0));
  check('selected idle conversation has its own flow', await page.locator('.ld-title-selected:not(.ld-title-active)').count() === 1);
  check('host positioning and stacking remain unchanged', await page.locator('.ld-surface').evaluate(el => getComputedStyle(el).position === 'static' && getComputedStyle(el).isolation === 'auto'));
  await page.evaluate(() => fixture.jobs([{id:'bash-1',kind:'bash',owner:'parent',label:'构建项目',status:'running',progress:'编译中'}]));
  await page.waitForSelector('.ld-orb');
  check('background process alone produces a truthful orb', await page.getByRole('button', {name:'后台任务 · 构建项目 · 运行中 · 编译中'}).count() === 1);
  await page.waitForSelector('.ld-title-selected.ld-title-active');
  check('background job activates its sidebar conversation', await page.locator('.ld-title-selected.ld-title-active').count() === 1);
  await page.evaluate(() => fixture.jobs([{id:'bash-1',kind:'bash',label:'构建项目',status:'failed',detail:'exit code: 1'}]));
  await page.waitForTimeout(650);
  check('failed job settles instead of running forever', await page.locator('.ld-orb').count() === 0);
  await page.evaluate(() => fixture.jobs([]));
  await page.evaluate(() => fixture.agents());
  await page.waitForSelector('.ld-working');
  check('four child orbs plus aggregate control', await page.locator('.ld-orb').count() === 4 && await page.getByLabel('展开其余 2 个任务').count() === 1);
  await page.waitForSelector('[aria-selected=true] .ld-title-selected.ld-title-active');
  check('selected and running sidebar styles coexist distinctly', await page.locator('[aria-selected=true] .ld-title-selected.ld-title-active').count() === 1 && await page.locator('.ld-title-muted').count() === 4);
  await page.locator('.ld-orb').first().focus();
  check('keyboard focus exposes task tooltip', await page.locator('.ld-tooltip').first().isVisible());
  await page.getByRole('button', {name:'展开其余 2 个任务'}).click();
  check('aggregate control exposes expanded state', await page.getByRole('button', {name:'收起任务'}).getAttribute('aria-expanded') === 'true' && await page.locator('.ld-orb').count() === 6);
  await page.getByRole('button', {name:'收起任务'}).click();
  await page.locator('.ld-title-selected').evaluate(el => { const range = document.createRange(); range.selectNodeContents(el); getSelection().removeAllRanges(); getSelection().addRange(range); });
  await page.waitForSelector('.ld-title-selecting');
  check('selected title remains opaque and hides decorative text', await page.locator('.ld-title-selected').evaluate(el => getComputedStyle(el).color !== 'rgba(0, 0, 0, 0)' && getComputedStyle(el, '::before').visibility === 'hidden'));
  await page.evaluate(() => getSelection().removeAllRanges());
  await page.evaluate(() => fixture.send());
  await page.waitForSelector('.ld-flight');
  check('flight is clipped to a plugin-owned layer', await page.locator('.ld-effects > .ld-flight').count() === 1);
  await page.waitForTimeout(1300);
  check('slower flight remains visible after 1.3 seconds', await page.locator('.ld-flight').count() === 1);
  check('submission emits a text orb without changing message text', await page.locator('[data-chat-flow-kind=user]').textContent() === '这是一条新消息');
  await page.waitForSelector('.ld-flight', { state: 'detached' });
  check('emission completes and cleans overlay', await page.locator('.ld-emitting').count() === 0);
  await page.evaluate(() => fixture.stream());
  await page.waitForSelector('.ld-stream');
  check('live paragraph and structured blocks animate', await page.locator('#ink').evaluate(el => el.getAnimations().length > 0) && await page.locator('#code').evaluate(el => el.getAnimations().length > 0));
  await page.waitForTimeout(500);
  await page.evaluate(() => fixture.append());
  await page.waitForTimeout(40);
  check('stream updates never reblur existing text', await page.locator('#ink').evaluate(el => el.getAnimations().length === 0));
  await page.screenshot({ path: path.join(out, 'desktop-fixture.png') });
  await page.evaluate(() => fixture.send()); await page.waitForSelector('.ld-flight');
  await page.evaluate(() => fixture.fail()); await page.waitForTimeout(60);
  check('failed send removes in-flight effects', await page.locator('.ld-flight').count() === 0);
  await page.evaluate(() => { for (let n = 0; n < 8; n++) fixture.send(`快速发送 ${n}`); });
  await page.waitForSelector('.ld-flight');
  check('rapid submissions keep one emission in flight', await page.locator('.ld-flight').count() === 1);
  await page.evaluate(() => fixture.switchSession()); await page.waitForTimeout(80);
  check('switching conversations hides parent agents and cancels pending emissions', await page.locator('.ld-orb,.ld-flight').count() === 0);
  await page.evaluate(() => fixture.switchSession()); await page.waitForTimeout(80);
  await page.evaluate(() => fixture.complete()); await page.waitForTimeout(650);
  check('completion dissolves all child orbs including hidden group members', await page.locator('.ld-orb').count() === 0);
  await page.emulateMedia({ reducedMotion: 'reduce' });
  await page.evaluate(() => fixture.agents(2)); await page.waitForTimeout(80);
  check('reduced motion disables bubbling', await page.locator('.ld-orb').first().evaluate(el => getComputedStyle(el).animationName === 'none'));
  await page.evaluate(() => fixture.send()); await page.waitForTimeout(80);
  check('reduced motion uses static send highlight', await page.locator('.ld-flight').count() === 0 && await page.locator('.ld-received').count() === 1);
  await page.setViewportSize({ width: 420, height: 760 });
  check('narrow desktop window has no horizontal overflow', await page.evaluate(() => document.documentElement.scrollWidth <= innerWidth));
  await page.getByLabel('灵动动效设置').click();
  check('settings use native modal focus containment', await page.locator('dialog').evaluate(el => el.matches(':modal') && el.contains(document.activeElement)));
  await page.getByLabel('启用动效').uncheck(); await page.waitForTimeout(50);
  check('settings disable all plugin surface and sidebar effects', await page.locator('.ld-surface,.ld-title,.ld-orb,.ld-flight').count() === 0);
  await page.getByLabel('启用动效').check(); await page.waitForTimeout(50);
  await page.getByRole('button', { name: '关闭', exact: true }).click();
  check('settings restore focus to trigger', await page.getByRole('button', {name:'灵动动效设置',exact:true}).evaluate(el => el === document.activeElement));
  await page.emulateMedia({ forcedColors: 'active' });
  check('high contrast keeps sidebar titles readable', await page.locator('.ld-title').first().evaluate(el => getComputedStyle(el).color !== 'rgba(0, 0, 0, 0)'));
  await page.evaluate(() => fixture.unmount()); await page.waitForTimeout(80);
  check('unload releases shared job roster', await page.evaluate(() => fixture.watches()) === 0);
  check('unload cleans CSS, overlays, surface and sidebar classes', await page.locator('style[data-plugin="dsh-lingdong"], .ld-surface, .ld-flight, .ld-title').count() === 0);
  await page.evaluate(() => mount()); await page.waitForSelector('.ld-surface');
  check('re-enable mounts exactly one stylesheet and dock', await page.locator('style[data-plugin="dsh-lingdong"]').count() === 1 && await page.locator('.ld-dock').count() === 1);
  check('no browser runtime errors', errors.length === 0);
  await writeFile(path.join(out, 'results.json'), JSON.stringify({ checks, errors, browser: browser.version(), fixture: true }, null, 2));
} finally { await browser.close(); server.close(); }
