import { createServer } from 'node:http';
import { readFile, mkdir, writeFile } from 'node:fs/promises';
import { fileURLToPath, pathToFileURL } from 'node:url';
import path from 'node:path';
import assert from 'node:assert/strict';
const root = fileURLToPath(new URL('../', import.meta.url));
const tools = process.env.DSH_TEST_MODULES;
const { build } = await import(tools ? pathToFileURL(path.join(tools, 'esbuild/lib/main.js')).href : 'esbuild');
const { chromium } = await import(tools ? pathToFileURL(path.join(tools, 'playwright-core/index.mjs')).href : 'playwright-core');
const out = path.resolve(process.env.DSH_TEST_OUTPUT || path.join(root, '../../work/browser-test'));
await mkdir(out, { recursive: true });
const fixture = await build({ absWorkingDir: root, entryPoints: ['test/fixture.jsx'], bundle: true, write: false,
  format: 'iife', platform: 'browser', nodePaths: tools ? [tools] : [] });
const html = `<!doctype html><meta charset="utf-8"><style>
*{box-sizing:border-box}body{margin:0;background:#f8fafb;color:#344454;font:15px system-ui;--dsw-alias-label-primary:#344454;--dsw-alias-bg-base:#f8fafb}#app{display:flex;height:100vh}aside{width:235px;background:#edf1f4;padding:30px 18px}aside small{display:block;margin:8px 0 30px;color:#84919d}aside [role=treeitem]{padding:12px 6px;display:flex;gap:10px}aside [role=treeitem]>span:last-child{margin-left:auto;font-size:10px}main{flex:1;min-width:0}header{height:76px;border-bottom:1px solid #879eaa22;display:flex;align-items:center;justify-content:space-between;padding:0 28px}[data-conversation-content]{height:calc(100vh - 76px);padding:40px 8%;display:flex;flex-direction:column}#messages{flex:1;overflow:auto}[data-chat-flow-kind]{padding:14px 0;line-height:1.8}[data-chat-flow-kind=user]{margin-left:auto;background:#e8eef2;border-radius:16px;padding:12px 18px;width:max-content;max-width:85%}[data-composer-seat]{border:1px solid #879eaa44;border-radius:20px;padding:22px;background:#fff}[data-composer-input]{outline:none;min-height:28px}pre{background:#edf1f4;border-radius:10px;padding:16px}header span{font-weight:500}@media(max-width:600px){aside{display:none}header{padding:0 15px}}
</style><div id="app"></div><script src="/fixture.js"></script><script src="/client.js"></script>`;
const server = createServer(async (req, res) => {
  res.setHeader('Content-Type', req.url.endsWith('.js') ? 'text/javascript' : 'text/html');
  res.end(req.url === '/fixture.js' ? fixture.outputFiles[0].contents : req.url === '/client.js' ? await readFile(path.join(root, 'lib/client.js')) : html);
});
await new Promise(resolve => server.listen(0, '127.0.0.1', resolve));
const browser = await chromium.launch({ executablePath: process.env.DSH_BROWSER || 'C:/Program Files (x86)/Microsoft/Edge/Application/msedge.exe', headless: true });
const context = await browser.newContext({ viewport: { width: 1200, height: 800 } });
const page = await context.newPage(), errors = [], checks = [];
page.on('pageerror', error => errors.push(error.message));
const check = (name, condition) => { assert.ok(condition, name); checks.push(name); console.log(`PASS ${name}`); };

try {
  await page.goto(`http://127.0.0.1:${server.address().port}`);
  await page.waitForSelector('.ld-surface');
  check('history never replays animations', await page.locator('#messages').evaluate(el=>el.getAnimations({subtree:true}).length===0));
  check('empty state has three adjacent solid balls on the native header background',await page.locator('.ld-capsule').evaluate(el=>getComputedStyle(el).borderStyle==='none' && getComputedStyle(el).backgroundColor==='rgba(0, 0, 0, 0)' && el.querySelectorAll('.ld-orb').length===3));
  await page.evaluate(()=>fixture.jobs([{id:'build',kind:'bash',owner:'parent',status:'running'}]));
  await page.waitForTimeout(100);
  check('background jobs do not activate balls, count, subscriptions or sidebar activity',await page.locator('.ld-working,.ld-row-active').count()===0 && await page.evaluate(()=>fixture.watches())===0);
  await page.evaluate(()=>fixture.agents(1));await page.waitForSelector('.ld-working');
  check('one working agent boils in its own header position',await page.locator('.ld-working').count()===1 && await page.locator('.ld-orb-wrap').evaluateAll(els=>els.every(n=>getComputedStyle(n).animationName==='none')));
  check('working ball stays a stable circle and only its small bubbles animate',await page.locator('.ld-working').evaluate(el=>{const body=el.querySelector('.ld-orb-body'),style=getComputedStyle(body);return style.clipPath==='none' && style.animationName==='none' && style.borderRadius==='50%' && [...el.querySelectorAll('i')].every(b=>getComputedStyle(b).animationName==='ld-boil')}));
  await page.evaluate(()=>fixture.agents(2));await page.waitForSelector('.ld-orbits-2');
  check('two working agents boil and orbit inside the header',await page.locator('.ld-orb-wrap').evaluateAll(els=>els.filter(n=>n.dataset.ldActive==='true').length===2 && els.filter(n=>n.dataset.ldActive==='true').every(n=>getComputedStyle(n).animationName==='ld-binary-orbit') && els.filter(n=>n.dataset.ldActive==='false').every(n=>getComputedStyle(n).animationName==='none') && new Set(els.filter(n=>n.dataset.ldActive==='true').map(n=>getComputedStyle(n).animationDelay)).size===2) && await page.locator('.ld-working').count()===2 && await page.locator('.ld-task-flight').count()===0);
  await page.evaluate(()=>fixture.agents(3));await page.waitForSelector('.ld-orbits-3');
  check('three working agents use intertwined trajectories',await page.locator('.ld-orb-wrap').evaluateAll(els=>els.every(n=>getComputedStyle(n).animationName==='ld-three-body')));
  const colors=await page.locator('.ld-orb-body').evaluateAll(els=>els.map(n=>getComputedStyle(n).backgroundColor));
  check('orbs are solid macOS red yellow green with no glass layers',new Set(colors).size===3 && await page.locator('.ld-orb-body').evaluateAll(els=>els.every(n=>getComputedStyle(n).backgroundImage==='none' && getComputedStyle(n).boxShadow==='none')));
  check('upward bubbles share their parent solid color',await page.locator('.ld-orb').evaluateAll(els=>els.every(n=>[...n.querySelectorAll('i')].every(b=>getComputedStyle(b).backgroundColor===getComputedStyle(n.querySelector('.ld-orb-body')).backgroundColor && getComputedStyle(b).animationName==='ld-boil'))));
  const positions=await page.locator('.ld-orb-wrap').evaluateAll(els=>els.map(n=>getComputedStyle(n).transform));await page.waitForTimeout(240);
  check('orbits actually move over time',JSON.stringify(positions)!==JSON.stringify(await page.locator('.ld-orb-wrap').evaluateAll(els=>els.map(n=>getComputedStyle(n).transform))));
  await page.evaluate(()=>fixture.finishOne());
  check('one completed agent starts an in-place return while two keep working',await page.locator('.ld-working').count()===2 && await page.locator('.ld-orb-wrap').evaluateAll(els=>els.some(n=>n.getAnimations().some(a=>a.effect?.getTiming().duration===520))));
  await page.waitForTimeout(600);
  check('after the return, two remaining agents orbit',await page.locator('.ld-orbits-2 .ld-orb-wrap[data-ld-active=true]').count()===2 && await page.locator('.ld-working').count()===2);
  await page.evaluate(()=>fixture.complete());
  check('completed balls arc back toward their original positions',await page.locator('.ld-orb-wrap').evaluateAll(els=>els.some(n=>n.getAnimations().some(a=>a.effect?.getTiming().duration===520))));
  await page.waitForTimeout(600);
  check('finished agents leave three calm balls in place',await page.locator('.ld-orb').count()===3 && await page.locator('.ld-working').count()===0);
  await page.evaluate(()=>fixture.agents(6));await page.waitForTimeout(80);
  check('six agents preserve the first three identities and colors',await page.locator('.ld-orb').count()===3 && JSON.stringify(colors)===JSON.stringify(await page.locator('.ld-orb-body').evaluateAll(els=>els.map(n=>getComputedStyle(n).backgroundColor))));
  await page.getByRole('button',{name:'查看 6 个子 Agent'}).click();check('capsule exposes all six agent states',await page.locator('.ld-task-list li').count()===6);await page.keyboard.press('Escape');
  check('Escape closes list and restores capsule focus',await page.locator('.ld-task-list').count()===0 && await page.locator('.ld-capsule').evaluate(n=>n===document.activeElement));
  const border = await page.locator('.ld-row-selected').evaluate(el=>({fill:getComputedStyle(el).backgroundImage,mask:getComputedStyle(el,'::after').maskComposite,blur:getComputedStyle(el,'::after').filter,glow:getComputedStyle(el,'::before').backgroundImage,pointer:getComputedStyle(el,'::before').pointerEvents}));
  check('sidebar glow is bound to the native row without extra children',await page.locator('.ld-row-selected').evaluate(el=>el.children.length===3 && getComputedStyle(el).position==='relative' && getComputedStyle(el).isolation==='auto') && await page.locator('.ld-edge').count()===0);
  check('sidebar keeps its original fill under irregular blurred light patches',border.fill==='none' && border.mask.split(',').every(x=>x.trim()==='add') && border.blur.includes('blur(') && border.glow.includes('radial-gradient') && border.pointer==='none');
  const moving=page.locator('[data-row-key="session:fifth"]');const oldY=await moving.evaluate(el=>el.getBoundingClientRect().y);
  await moving.evaluate(el=>el.parentElement.querySelector('small').after(el));
  check('native row and its glow move together when the sidebar reorders',await moving.evaluate((el,previous)=>el.getBoundingClientRect().y<previous && el.classList.contains('ld-row') && getComputedStyle(el,'::before').backgroundImage.includes('radial-gradient'),oldY));
  const spot=await page.locator('.ld-row-selected').evaluate(n=>getComputedStyle(n,'::before').getPropertyValue('--ld-ax'));await page.waitForTimeout(150);
  check('edge light spots flow instead of staying in a fixed frame',spot!==await page.locator('.ld-row-selected').evaluate(n=>getComputedStyle(n,'::before').getPropertyValue('--ld-ax')));
  await page.evaluate(()=>{window.flightFrames=[];window.recording=true;function read(){const el=document.querySelector('.ld-message-flight');if(el){const r=el.getBoundingClientRect(),target=document.querySelector('#messages [data-chat-flow-kind=user]:last-child .LdtX1G_bubble'),tr=target.getBoundingClientRect();window.flightFrames.push({phase:el.dataset.ldPhase,x:r.x,y:r.y,w:r.width,h:r.height,tx:tr.x,ty:tr.y,tw:tr.width,th:tr.height,scale:el.querySelector('.ld-flight-copy').style.transform,text:el.querySelector('.ld-flight-copy').textContent});}if(window.recording)requestAnimationFrame(read)}requestAnimationFrame(read);fixture.send('这是一条真实收拢和展开的消息');});
  await page.waitForSelector('.ld-message-flight');
  check('native message actions remain visible during text flight',await page.locator('[data-native-actions]').last().evaluate(el=>getComputedStyle(el).opacity==='1'));
  check('host message stays accessible and visually held during flight',await page.locator('#messages .LdtX1G_bubble').last().evaluate(el=>getComputedStyle(el).opacity==='0' && el.textContent.includes('真实收拢')));
  check('shrinking text becomes a moving color ball',await page.locator('.ld-flight-core').evaluate(el=>getComputedStyle(el).backgroundImage.includes('conic-gradient') && getComputedStyle(el).animationName==='ld-message-flow'));
  await page.screenshot({path:path.join(out,'send-gather.png')});
  await page.evaluate(()=>fixture.confirm());await page.waitForTimeout(70);
  check('optimistic replacement remains hidden until its copy arrives',await page.locator('#messages .LdtX1G_bubble').last().evaluate(el=>getComputedStyle(el).opacity==='0'));
  await page.waitForFunction(()=>window.flightFrames.some(frame=>frame.phase==='expand'));await page.screenshot({path:path.join(out,'send-expand.png')});
  await page.waitForSelector('.ld-message-flight',{state:'detached'});await page.evaluate(()=>window.recording=false);
  const frames=await page.evaluate(()=>window.flightFrames);
  check('full text survives gathering without slicing',frames.length>10 && frames.every(f=>f.text==='这是一条真实收拢和展开的消息'));
  check('all three continuous phases are rendered',new Set(frames.map(f=>f.phase)).size===3);
  check('gather shrinks the entire text with scale instead of cropping',new Set(frames.filter(f=>f.phase==='gather').map(f=>f.scale)).size>3);
  const final=frames.at(-1);check('expansion ends at the actual message bounds',Math.abs(final.x-final.tx)<3 && Math.abs(final.y-final.ty)<3 && Math.abs(final.w-final.tw)<4 && Math.abs(final.h-final.th)<4);
  check('message restored after expansion',await page.locator('#messages .LdtX1G_bubble').last().evaluate(el=>getComputedStyle(el).opacity==='1'));
  // The input is deliberately resized and scrolled before sending a longer multiline message.
  await page.evaluate(()=>{const el=document.querySelector('[data-composer-input]');el.style.cssText='font-size:21px;line-height:31px;width:360px;height:100px;overflow:auto;white-space:pre-wrap';fixture.send('第一行，保持真实字号和换行。\n第二行，这段文字必须完整地收拢。\n第三行，展开后准确到达消息位置。');});
  await page.waitForSelector('.ld-message-flight');
  check('gather uses real multiline input dimensions and font',await page.locator('.ld-flight-copy').first().evaluate(el=>el.style.width==='360px' && el.style.height==='100px' && getComputedStyle(el.firstElementChild).fontSize==='21px' && el.textContent.includes('第三行')));
  await page.evaluate(()=>{document.querySelector('#messages [data-chat-flow-kind=user]:last-child .LdtX1G_bubble').style.marginRight='36px';fixture.confirm()});
  await page.waitForSelector('.ld-message-flight',{state:'detached'});
  check('layout changes during flight restore the correct new target',await page.locator('#messages .LdtX1G_bubble').last().evaluate(el=>getComputedStyle(el).opacity==='1'));
  await page.evaluate(()=>fixture.send('失败时必须恢复'));await page.waitForSelector('.ld-message-flight');await page.evaluate(()=>fixture.fail());await page.waitForTimeout(70);
  check('send failure immediately cancels and restores native message',await page.locator('.ld-message-flight').count()===0 && await page.locator('#messages .LdtX1G_bubble').last().evaluate(el=>getComputedStyle(el).opacity==='1'));
  await page.evaluate(()=>fixture.send('切换会话时恢复'));await page.waitForSelector('.ld-message-flight');await page.evaluate(()=>fixture.switchSession());await page.waitForTimeout(80);
  check('session switch cleans all transient visuals and leaves idle header balls',await page.locator('.ld-flight,.ld-working').count()===0 && await page.locator('.ld-orb').count()===3);
  await page.evaluate(()=>fixture.switchSession());await page.waitForTimeout(80);await page.evaluate(()=>fixture.complete());await page.waitForTimeout(500);
  check('completed agents settle back to three idle balls',await page.locator('.ld-orb').count()===3 && await page.locator('.ld-working').count()===0);
  await page.emulateMedia({reducedMotion:'reduce'});await page.evaluate(()=>fixture.agents(3));await page.waitForTimeout(80);
  check('reduced motion separates three balls without animation',await page.locator('.ld-orb-wrap').evaluateAll(els=>els.every(n=>getComputedStyle(n).animationName==='none') && new Set(els.map(n=>getComputedStyle(n).transform)).size===3));
  await page.evaluate(()=>fixture.send('减少动态效果'));await page.waitForTimeout(70);check('reduced motion uses static send feedback',await page.locator('.ld-flight').count()===0 && await page.locator('.ld-received').count()===1);
  await page.setViewportSize({width:420,height:760});check('narrow header has no horizontal overflow',await page.evaluate(()=>document.documentElement.scrollWidth<=innerWidth));
  await page.locator('.ld-capsule').click();await page.getByRole('button',{name:'灵动动效设置',exact:true}).click();check('settings modal contains focus',await page.locator('dialog').evaluate(el=>el.matches(':modal') && el.contains(document.activeElement)));
  await page.getByLabel('启用动效').uncheck();await page.waitForTimeout(80);check('disable removes surface, row glow and orb effects',await page.locator('.ld-surface,.ld-row,.ld-orb').count()===0);
  await page.getByLabel('启用动效').check();await page.getByRole('button',{name:'关闭',exact:true}).click();await page.keyboard.press('Escape');
  await page.emulateMedia({reducedMotion:'no-preference'});await page.setViewportSize({width:1200,height:800});await page.waitForTimeout(200);await page.screenshot({path:path.join(out,'desktop-fixture.png')});
  await page.evaluate(()=>fixture.stream());await page.waitForSelector('.ld-stream');check('native structured content retained',await page.locator('#code code').textContent()==='const motion = "quiet";');
  await page.evaluate(()=>fixture.unmount());await page.waitForTimeout(80);check('unload cleans all styles, animations and edge nodes',await page.locator('style[data-plugin="dsh-lingdong"],.ld-edge,.ld-flight,.ld-surface,.ld-row').count()===0);
  await page.evaluate(()=>mount());await page.waitForSelector('.ld-surface');check('re-enable has exactly one style and capsule',await page.locator('style[data-plugin="dsh-lingdong"]').count()===1 && await page.locator('.ld-capsule').count()===1);
  check('no browser runtime errors',errors.length===0);
  await writeFile(path.join(out,'results.json'),JSON.stringify({checks,errors,browser:browser.version(),fixture:true,frames},null,2));
} finally { await browser.close();server.close(); }
